# Maciej Wicha IMST I2S 1.5
# Zadanie 1 - PFwChO

name: PFwChO Zad1 FibCalc GitHub Action Workflow
on:
  # Możliwość uruchamiania ręcznego workflow
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    # Wybranie systemu operacyjnego Ubuntu 20.04 jako podstawę do budowania
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      # Skonfigurowanie dockera + buildx
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # Logowanie do Dockerhuba
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}

      # Logowanie do GitHub Packages
      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GIT_HUB_TOKEN}}

      #Semantic versioning
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/MaWickos/FibCalc
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      # Zbudowanie i wypchniecie obrazu na Dockerhuba
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,src=docker.io/mawickos/fibcalc:obowiazkowe-cache
          cache-to: type=registry,ref=docker.io/mawickos/fibcalc:obowiazkowe-cache
          platforms: linux/amd64, linux/arm64
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
